### ISSUE TITLE
Support for Dutch language

### ISSUE THREAD

**Issue by RoodFruit** [Sammyjo20/Wagonwheel#13]
To support Dutch language (which is 'nl'), add the following please ^^

```
<?php

return [
    'message' => 'Is de e-mail niet goed leesbaar?',
    'link'    => 'Bekijk het in de browser',
];

**Comment by Sammyjo20** [comment]
Hey! 👋🏼 

I'll get this added in later today for you @RoodFruit 👍

**Comment by Sammyjo20** [comment]
Referenced in https://github.com/Sammyjo20/Wagonwheel/pull/14
