### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by Jhnbrn90** [Sammyjo20/Wagonwheel#3]
Dear @Sammyjo20 

I would like to add some tests for your package and I see that you want to support Laravel 7 and 8. To be able to use model factories in these tests I suggest we make use of the legacy factories, [as described in the readme](https://github.com/orchestral/testbench#class-illuminatedatabaseeloquentfactory-not-found) of Orchestra Testbench. 

Alternatively, the repository could be split up in a version that supports up to Laravel 7 and one that supports Laravel 8 and beyond. 

With your approval I'd like to submit a PR these days to add some tests using the legacy model factories approach. 

What do you think would be best?

**Comment by Sammyjo20** [comment]
Hi @Jhnbrn90 Thanks very much for taking the time to help improve Wagonwheel, I appreciate it - let me just run it past @ryangjchander as I know he is also building tests this weekend -so I wouldn't want you to put the hard work in to build Legacy tests when he builds his own I hope that's okay!

**Comment by Jhnbrn90** [comment]
@Sammyjo20 Right! 👍😊 I'm glad I created this issue first. I'll await the work of Ryan in that case and fill in if necessary. 

I wanted to add the basic tests in the first place as I also wanted add a feature, namely to allow to store the online emails indefintitely (by configuration). Would you be open to a PR that facilitates this?

**Comment by Sammyjo20** [comment]
Hi @Jhnbrn90 - I’ve decided to drop support for Laravel 7 in my next release, which means all tests can be written under the assumption that it will be only Laravel 8 and above. If you’re still happy to write some tests, me and Ryan will review them. Thanks so much!
